name: Publicação automática
on:
# on: [workflow_dispatch]
  # nosso script será executado sempre quando houver push e pull request nas branches destacadas abaixo
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
 
    - name: Cria um arquivo temporário para a chave privada 
      run: |
               echo "${{ secrets.KEY }}" > /tmp/private_key
               chmod 600 /tmp/private_key
 
    - name: Criando a pasta da aplicação e acertando diretório...
      run: |
               ssh -i /tmp/private_key -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ubuntu@${{ secrets.HOST }} \
               sudo mkdir -p /var/www/html/topicos-2
    - name: Ajustar permissões no servidor de Produção
      run: |
          ssh -i /tmp/private_key -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ubuntu@${{ secrets.HOST }} "sudo chown -R ubuntu:ubuntu /var/www/html/topicos-2 && sudo chmod -R 755 /var/www/html/topicos-2"

    - name: Transferindo os arquivos da aplicação
      run: |
            scp -i /tmp/private_key -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -r \
            ${{ github.workspace }}/* ubuntu@${{ secrets.HOST }}:/var/www/html/topicos-2

    - name: Restaurando a aplicação
      run: |
             ssh -i /tmp/private_key -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ubuntu@${{ secrets.HOST }} \
             cd /var/www/html/topicos-2 && composer install \

    - name: Reiniciando o serviço da aplicação
      run: |
             ssh -i /tmp/private_key -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ubuntu@${{ secrets.HOST }} \
             sudo systemctl restart apache2

    - name: Limpa o arquivo de chave privada após uso
      run: |
           rm /tmp/private_key
